### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [Bernie-2016/fieldthebern-android#530]
F-Droid is a FOSS-only app story for the Android platform. It would be great to have this app there, as it increases visibility for Bernie's campaign.

Here's how to include it there: https://f-droid.org/contribute/

**Comment by patrickcousins** [comment]
Not going to rule this out but this is not a priority right now.

**Comment by pizzamaker** [comment]
Thanks for being receptive to the idea. I took the liberty of adding it to the submission queue: https://f-droid.org/forums/topic/field-the-bern/

**Comment by pizzamaker** [comment]
Could you provide a gradle flavor without play-services and crashlytics? It's currently an obstacle for inclusion.

**Comment by patrickcousins** [comment]
@pizzamaker While I personally support F-droid, this is not something we have the dev time to cover right now.  Please don't submit the app to F-Droid or any other alternative stores.
